config/routes.rb
Rails.application.routes.draw do
  get 'paid_area/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iota_service.rb
class IotaService

  require 'iota'

  def self.buy_request
    transfer = IOTA::Models::Transfer.new(
        address: 'EVLVJYD9BDMKJTEWELUCGLMNQSIBAAWWLVGZCFRVLVPDUPLCUVDOVHXJ9NTFWNIZ9DKCZFOOGZPMXPTLBWETFZTFLX',
        value: 1
    )
    depth = 3
    minWeightMagnitude = 9
    PayPerRequest::Application.config.account.sendTransfer(depth, minWeightMagnitude, [transfer], {})
    PayPerRequest::Application.config.balance = PayPerRequest::Application.config.balance - 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @account = PayPerRequest::Application.config.account
    @balance = PayPerRequest::Application.config.balance
  end
end

app/controllers/paid_area_controller.rb
class PaidAreaController < ApplicationController

  before_action :do_payment

  def index
      @balance = PayPerRequest::Application.config.balance
  end

  private

  def do_payment

    if PayPerRequest::Application.config.balance > 0.0
      ## good to go
      IotaService.buy_request
    else
      flash[:error] = 'You cant do this, the pot is empty'

      redirect_to root_path
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paid_area_helper.rb
module PaidAreaHelper
end

app/views/home/index.html.erb
<% if flash[:error] %>
  <div class="notice"><%= flash[:error] %></div>
<% end %>

<h1>Pay per Request (ppr) demo.</h1>


<p>Each request costs 1 iota.</p>

<p>Press the button below, to pay the price and get to the secret area.</p>

<p>Current available IOTA in the pot: <%= @balance %></p>

<p>You can spend some iota to this address, but care - all others can also use the iota to pay requests.</p>
<p>Donations address</p>
<p><%= @account.latestAddress %></p>
<p>Lets go!</p>

<%= link_to "paid area", paid_area_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayPerRequest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paid_area/index.html.erb
<h1>This is the paid area</h1>
<h2>You (or someone else) have paid for this, have fun! </h2>
<p>Current available IOTA in pot: <%= @balance %></p>

<p>Attention: page reloading also cost iota!</p>